### ISSUE TITLE
Cannot use external hard drive with NodeODM

### ISSUE THREAD

**Issue by MiguelMartinGit** [OpenDroneMap/NodeODM#200]
I use  'sudo docker run -p 3000:3000 -v /mnt/e/data:/var/www/data --gpus all opendronemap/nodeodm:gpu' and after create a task on the API, I've had this error : 

Cannot move tmp/3743938e-953c-42a8-93e8-5ed010c80e83, probably caused by antivirus software (please disable it or add an exception), retrying (1)...
internal/validators.js:223
    throw new ERR_INVALID_CALLBACK(callback);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 2000
    at setTimeout (timers.js:141:3)
    at /var/www/libs/taskNew.js:307:33
    at /var/www/node_modules/mv/index.js:101:27
    at cb (/var/www/node_modules/ncp/lib/ncp.js:255:23)
    at onError (/var/www/node_modules/ncp/lib/ncp.js:247:12)
    at /var/www/node_modules/ncp/lib/ncp.js:159:16
    at FSReqCallback.oncomplete (fs.js:180:23) {
  code: 'ERR_INVALID_CALLBACK'

I disabled the antivirus, put an exception on the file in question but that did not change anything.

Someone can help me pls ?

**Comment by pierotofy** [comment]
This should have been fixed some time ago. 🙏 Update and feel free to re-open if the issue persists.
