### ISSUE TITLE
Syntax Errors. Please have a look or check if versions are okay?

### ISSUE THREAD

**Issue by hitesh4** [OpenDroneMap/NodeODM#78]
nvidia@tegra-ubuntu:~/NodeODM$ node index.js --test
/home/nvidia/NodeODM/libs/S3.js:89
                        }, (2 ** file.retries) * 1000);
                               ^

SyntaxError: Unexpected token *
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nvidia/NodeODM/libs/Task.js:33:12)
nvidia@tegra-ubuntu:~/NodeODM$ nodejs -v
v6.17.1
nvidia@tegra-ubuntu:~/NodeODM$ npm -v
6.9.0
nvidia@tegra-ubuntu:~/NodeODM$

**Comment by hitesh4** [comment]
Also another doubt. Where do the files go after complete processing? I was able to run it on my local machine, but not on jetson TX2. On the local machine, it said deleted temporary files something like that, can't I store those files or not let it delete the files until I see them.

**Comment by pierotofy** [comment]
I'd upgrade nodejs version. The software has been tested with version10.x. For other questions, let's move the conversation over to https://community.opendronemap.org. Thanks!!
